import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import jsPDF from "jspdf";
import { getRiskLevel } from "@/lib/cityData";

interface ReportProps {
  cityName: string;
  liveTemp: number;
  adjustedTemp: number;
  riskScore: number;
  treeCover: number;
  density: number;
  feelsLike: number;
}

export default function ReportDownload(props: ReportProps) {
  const download = () => {
    const doc = new jsPDF();
    const risk = getRiskLevel(props.riskScore);

    doc.setFontSize(20);
    doc.text("Urban Heat Intelligence Report", 20, 25);

    doc.setFontSize(12);
    doc.text(`City: ${props.cityName}`, 20, 40);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 48);

    doc.setFontSize(14);
    doc.text("Heat Analysis", 20, 65);
    doc.setFontSize(11);
    doc.text(`Live Temperature: ${props.liveTemp.toFixed(1)}°C`, 25, 75);
    doc.text(`Adjusted Temperature: ${props.adjustedTemp.toFixed(1)}°C`, 25, 83);
    doc.text(`Feels Like: ${props.feelsLike.toFixed(1)}°C`, 25, 91);
    doc.text(`Heat Risk Score: ${props.riskScore.toFixed(0)}/100`, 25, 99);
    doc.text(`Risk Level: ${risk}`, 25, 107);

    doc.setFontSize(14);
    doc.text("Environmental Parameters", 20, 125);
    doc.setFontSize(11);
    doc.text(`Tree Cover: ${props.treeCover}%`, 25, 135);
    doc.text(`Urban Density: ${props.density}%`, 25, 143);

    doc.setFontSize(9);
    doc.text("This report uses real-time weather data and urban environmental patterns.", 20, 275);
    doc.text("Generated by Urban Heat Intelligence System Pro", 20, 282);

    doc.save(`heat-report-${props.cityName.toLowerCase()}.pdf`);
  };

  return (
    <Button onClick={download} variant="outline" className="gap-2">
      <Download className="h-4 w-4" /> Download Report (PDF)
    </Button>
  );
}
